In [189]:
import pandas as pd

In [190]:
df = pd.read_csv('tickets.csv')

In [191]:
df.head(-10)

Title  \
0                                 Need Ethernet access   
1    Create new account and share the username and ...   
2                       FW: Myspace Login Issue-- Ania   
3                    Login credetials are not working.   
4              New Account is needed for a new joinee.   
..                                                 ...   
221  System behaves strangely, blue screen appears ...   
222            System showing a blue screen at startup   
223  The account was blocked due to 3 wrong passwor...   
224                      The computer will not turn on   
225                         The desktop is not working   

                                            Resolution  
0    Please connect the LAN cable to the red port o...  
1    Go to URL : accountsetup.com, Enter personal d...  
2    Go to URL : password.reset.com, Enter you logi...  
3    Go to URL : password.reset.com, Enter you logi...  
4    Go to URL : accountsetup.com, Enter personal d...  
..                                                 ...  
221  Press F8 button on system start, Choose safe m...  
222  1. Hold the power button until system gets shu...  
223  Unlocked the account and new password is sent ...  
224                                Contact IT support.  
225  Please check the Power cables are properly plu...  

[226 rows x 2 columns]

## Cleaning

In [192]:
#lets remove punctuations if any 

punct = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
sample_str = "Hi! , he wanted me to build --- a chatbot and he went away."


In [193]:
nopunct = ''
for char in sample_str:
    if(char not in punct):
        nopunct = nopunct + char

In [194]:
nopunct

'Hi  he wanted me to build  a chatbot and he went away'

In [195]:
# use regex to clean to avoind for loop and work faster

import re 
sampstr= "should. I. Build?"
sampstr= re.sub(r'[^\w\s]','',sampstr)

In [196]:
sampstr

'should I Build'

## LETS Tokenize
#### -breaking down of sentences into word

In [197]:
import nltk
nltk.download ('punkt')
nltk.download('wordnet')


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\krant\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\krant\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [198]:
nltk.word_tokenize('lets have some fun baby!') #its basically uses python split function

['lets', 'have', 'some', 'fun', 'baby', '!']

## STOP WORD REMOVING 
##### - removes the word which doesnt hold much value 

In [199]:
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
print(stop_words)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [200]:
stop_words.append('wwwwwwkkkkk')

In [201]:
stop_words

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

## Stemming
#### - To reduce the words to the word stems like males to male , playing to play ---if we dont do this male and males will process as different words

#### may not be efficient method but simple 

In [202]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()
mystr = ' Bots are the future assistants.'
mystr = nltk.word_tokenize(mystr)
for word in mystr:
    print (stemmer.stem(word))

bot
are
the
futur
assist
.


## Lemmatization - 
####  efficient way of reducing a word to its root form , often time its harder to create lemmatizer with new language then stemming  

In [203]:
from nltk.stem import WordNetLemmatizer
lem = WordNetLemmatizer()
mystr = ' Bots are the future assistants, but mice were everywhere'
mystr = nltk.word_tokenize(mystr)
for word in mystr:
    print(lem.lemmatize(word))

Bots
are
the
future
assistant
,
but
mouse
were
everywhere


In [204]:
#lets apply these data

In [205]:
df['Title'][1:5]

1    Create new account and share the username and ...
2                       FW: Myspace Login Issue-- Ania
3                    Login credetials are not working.
4              New Account is needed for a new joinee.
Name: Title, dtype: object

In [206]:
# lets apply to our data set

In [207]:
''''
lem = WordNetLemmatizer()
for index,row in df.iterrows():
    filter_text = []
    text = row['Title']
    text = re.sub(r'[^\w\s]','',text) #cleaning with reg EX
    words = nltk.word_tokenize(text) # tokenization
    words = [w for w in words if not w in stop_words] #stopword removal
    
    #print(words)
    #lemmatization
    for word in words :
        filter_text.append(lem.lemmatize(word))
        #filter_text = filter_text + ' '+ lem.lemmatize(word)
    print(filter_text)
    #df.ix[index , 'Title'] = filter_text
 
#if any suspicious words are present like other languages , symbols ets , you can add those to the stopwords and remove that 
# lets delemmatize this 
'''

"'\nlem = WordNetLemmatizer()\nfor index,row in df.iterrows():\n    filter_text = []\n    text = row['Title']\n    text = re.sub(r'[^\\w\\s]','',text) #cleaning with reg EX\n    words = nltk.word_tokenize(text) # tokenization\n    words = [w for w in words if not w in stop_words] #stopword removal\n    \n    #print(words)\n    #lemmatization\n    for word in words :\n        filter_text.append(lem.lemmatize(word))\n        #filter_text = filter_text + ' '+ lem.lemmatize(word)\n    print(filter_text)\n    #df.ix[index , 'Title'] = filter_text\n \n#if any suspicious words are present like other languages , symbols ets , you can add those to the stopwords and remove that \n# lets delemmatize this \n"

In [208]:
## lets analyse by applying NLP

In [209]:
## Some of the techniques we need to know before going is BOW , TF-idf , W2V

## BOW

In [210]:
from sklearn.feature_extraction.text import CountVectorizer

In [211]:
text = "its main aim is to remove the poverty and \ enable the dignified life."

count_vec = CountVectorizer() # distinct words
count_occurs = count_vec.fit_transform([text]) # it holds the frequency of each word


In [212]:
# lets create a data frame 

count_occur_df = pd.DataFrame(
    
    (count,word) for word,count in  
      zip(count_occurs.toarray().tolist()[0],
     count_vec.get_feature_names()))

count_occur_df.columns = ['Word' , 'Count']
count_occur_df.sort_values('Count', ascending = False , inplace = True)
count_occur_df.head()

Word  Count
10        the      2
0         aim      1
1         and      1
2   dignified      1
3      enable      1

In [213]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [ 
    
    'the document is the document ', 'india is my country ', 'please docoument the code that we apply.', ' does makes sence?'
]


vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())

['apply', 'code', 'country', 'docoument', 'document', 'does', 'india', 'is', 'makes', 'my', 'please', 'sence', 'that', 'the', 'we']


In [214]:
print(X.toarray()) # each row indicates a sentence and eaach value indiacate frequency of word  whioch is in corpus

[[0 0 0 0 2 0 0 1 0 0 0 0 0 2 0]
 [0 0 1 0 0 0 1 1 0 1 0 0 0 0 0]
 [1 1 0 1 0 0 0 0 0 0 1 0 1 1 1]
 [0 0 0 0 0 1 0 0 1 0 0 1 0 0 0]]


In [215]:
#another example
#ngram will take two words as two words #it only works with the unique word
vectorizer2 = CountVectorizer(analyzer = 'word' , ngram_range =(2,2))
X2 = vectorizer2.fit_transform(corpus)
print(vectorizer2.get_feature_names())
print(X2.toarray())


['code that', 'docoument the', 'document is', 'does makes', 'india is', 'is my', 'is the', 'makes sence', 'my country', 'please docoument', 'that we', 'the code', 'the document', 'we apply']
[[0 0 1 0 0 0 1 0 0 0 0 0 2 0]
 [0 0 0 0 1 1 0 0 1 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 1 1 1 0 1]
 [0 0 0 1 0 0 0 1 0 0 0 0 0 0]]


## tf-IDF

### - Term freq(tf) = count(each word)/ total words

### - inverse doc freq(IDF) = log(N/df)

In [216]:
#eX -

a = 'the climate is good'
b = 'the climate is hot'

bow_a = a.split(' ')
bow_b = b.split (' ')
#tokenization

In [217]:
bow_a

['the', 'climate', 'is', 'good']

In [218]:
unqwords = set(bow_a).union(set(bow_b))



In [219]:
unqwords

{'climate', 'good', 'hot', 'is', 'the'}

In [220]:
 #creating a dictionary with count of words

In [221]:
no_words_a = dict.fromkeys(unqwords,0)
for word in bow_a :
    no_words_a[word] +=1
no_words_b = dict.fromkeys(unqwords, 0 )
for word in bow_b:
    no_words_b[word] +=1

In [222]:
print(no_words_a)
no_words_b

{'is': 1, 'hot': 0, 'the': 1, 'climate': 1, 'good': 1}


{'is': 1, 'hot': 1, 'the': 1, 'climate': 1, 'good': 0}

In [223]:
def computeTF(wordDict , bow):
    tfDict = {}
    bowcount = len(bow)
    for word, count in wordDict.items():
        tfDict[word] = count / float(bowcount)
    return tfDict

In [224]:
tfa = computeTF(no_words_a,bow_a)
tfb = computeTF(no_words_b, bow_b)

In [225]:
tfa

{'is': 0.25, 'hot': 0.0, 'the': 0.25, 'climate': 0.25, 'good': 0.25}

In [226]:
tfb

{'is': 0.25, 'hot': 0.25, 'the': 0.25, 'climate': 0.25, 'good': 0.0}

In [227]:
# similarly for idf ]
#then multiply it with TF



In [228]:
# OR WE have sklearn lib which is pre implemented

In [229]:
from sklearn.feature_extraction.text import TfidfVectorizer


In [230]:

vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform(df['Title']) #fit will create the dictionory ad transform will applky tfidf 

In [231]:
vectors

<236x270 sparse matrix of type '<class 'numpy.float64'>'
	with 1596 stored elements in Compressed Sparse Row format>

In [232]:
vectorizer.get_feature_names()

['able',
 'access',
 'account',
 'act',
 'acting',
 'addresses',
 'allowed',
 'am',
 'among',
 'an',
 'and',
 'ania',
 'anti',
 'any',
 'anymore',
 'app',
 'appearing',
 'appears',
 'application',
 'are',
 'at',
 'attachment',
 'attachments',
 'attempts',
 'authorization',
 'available',
 'battery',
 'be',
 'because',
 'beginning',
 'behave',
 'behaves',
 'behaving',
 'being',
 'between',
 'bin',
 'black',
 'blocked',
 'bloqueó',
 'blue',
 'borders',
 'by',
 'can',
 'cause',
 'clean',
 'client',
 'closing',
 'come',
 'compte',
 'computer',
 'configuration',
 'configure',
 'configured',
 'connect',
 'connection',
 'contraseña',
 'cookies',
 'correctly',
 'could',
 'crashes',
 'create',
 'credentials',
 'credetials',
 'cuenta',
 'damage',
 'database',
 'de',
 'debido',
 'delete',
 'desktop',
 'determine',
 'disc',
 'disk',
 'display',
 'distorted',
 'do',
 'does',
 'doesn',
 'doing',
 'down',
 'drive',
 'due',
 'eliminate',
 'email',
 'emails',
 'enter',
 'equipped',
 'erase',
 'erratical

### Lets build text classifier

In [233]:
#features , labels 
#train and validation

#label encoding , train text splitting


In [234]:
from sklearn import model_selection , preprocessing #
from sklearn.metrics import accuracy_score

In [235]:
x_train , x_valid , y_train , y_valid = model_selection.train_test_split(vectors , df['Resolution'], test_size = 0.2)

In [236]:
print(x_train.shape , x_valid.shape)

(188, 270) (48, 270)


In [237]:
y_valid

9      We regret for the inconvinience caused. The is...
102    Press F8 button on system start, Choose safe m...
199     Thankfully a missing printer installation dis...
168     As with most computer errors, your first step...
234     Users who have an optical mechanical mouse (m...
145    changed network settings to Bridged and config...
99      Make sure both the computer and monitor are o...
76      Microsoft Internet Explorer users can go to '...
135     Verify that the network cable is properly con...
51      If you're running any version of Microsoft Wi...
186     The keys on a keyboard are only clipped on, w...
166     If the resolution was recently changed it is ...
75      If you are running Microsoft Windows 7, Windo...
177    Go to URL : accountsetup.com, Enter personal d...
139    Go to URL : password.reset.com, Enter you logi...
215    Go to network tab from bottom right corner, ch...
69     Go to network tab from bottom right corner, ch...
148    Go to network tab from b

In [238]:
# we can't give labels as a resulution to ml algo so encoding 


In [239]:
# label encoding to the target variable 

encoder = preprocessing.LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_valid = encoder.transform(y_valid) # we are not uysing fit(which created dict in valid becz we want follow the same dict )

In [240]:
y_valid

array([48, 45, 19,  2, 26, 49, 13, 15, 28, 10, 20,  8,  9, 35, 36, 38, 38,
       38, 36, 47, 20, 34, 38,  4,  9, 37, 12, 32, 36, 46, 27, 19, 11, 46,
       38,  7, 48, 45, 25, 36,  1, 10,  8, 15, 22,  7, 34,  5])

In [241]:
#lets start modelling - Logistic reg

from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [242]:
lgr = LogisticRegression()
lgr.fit(x_train , y_train)

LogisticRegression()

In [243]:
y_predict = lgr.predict(x_valid)

In [244]:
print('accuracy of log reg classifier on test set : {:.2f}'.format(metrics.accuracy_score(y_predict , y_valid)))

accuracy of log reg classifier on test set : 0.75


In [247]:
lgr.predict(vectorizer.transform(['my keybourd is not working'])) # if i fit again it created another dictionor and labels may change may be due to new words which our model not seen

array([38])

In [ ]:
# we can do much advanced processing and modelling for better accuracy then we can make flask app with this pipe lik